additionalArguments:
  - --entrypoints.websecure.http.tls.domains[0].main=*.com
  - --entrypoints.websecure.http.tls.domains[0].sans=*.com
  - --accesslog=true
  - --tracing=false

ingressRoute:
  dashboard:
    enabled: false

logs:
  general:
    level: DEBUG

## Static configuration
serversTransport:
  insecureSkipVerify: true

service:
  enabled: true
  type: LoadBalancer
  # Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
